import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Deployment } from "@/lib/schemas/deployment";
import type { Tool } from "@/lib/schemas/tool";

/**
 * Post-deployment report — a REAL generated PDF (not mocked). Includes the
 * scorecard (clinical/workflow/referral/cost/equity) or trial endpoints, the
 * SCALE/EXTEND/STOP recommendation, and the handover ownership plan. Runs
 * client-side (pdf-lib) and triggers an actual file download.
 */
const TEAL = rgb(0.059, 0.431, 0.337);
const INK = rgb(0.055, 0.078, 0.067);
const MUTED = rgb(0.42, 0.463, 0.435);

export async function downloadReportPdf(dep: Deployment, tool: Tool, hospitalName: string): Promise<void> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]);
  const serif = await pdf.embedFont(StandardFonts.TimesRomanBold);
  const sans = await pdf.embedFont(StandardFonts.Helvetica);
  const sansBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const left = 56;
  let y = 786;
  const line = (text: string, opts: { size?: number; font?: typeof sans; color?: typeof INK; gap?: number } = {}) => {
    page.drawText(text, { x: left, y, size: opts.size ?? 11, font: opts.font ?? sans, color: opts.color ?? INK });
    y -= opts.gap ?? 16;
  };
  const rule = () => { page.drawRectangle({ x: left, y: y + 6, width: 595 - left * 2, height: 0.6, color: rgb(0.85, 0.836, 0.784) }); y -= 12; };

  page.drawText("CLEARPATH", { x: left, y, size: 10, font: sansBold, color: TEAL }); y -= 34;
  line(`${dep.kind === "trial" ? "Clinical trial" : "Deployment"} report — ${tool.name}`, { size: 20, font: serif, gap: 22 });
  line(`${hospitalName} · day ${dep.dayOf} of ${dep.totalDays}`, { size: 11, color: MUTED, gap: 18 });
  rule();

  if (dep.recommendation) {
    line("Recommendation", { size: 13, font: sansBold, gap: 18 });
    line(dep.recommendation.decision, { size: 18, font: serif, color: TEAL, gap: 18 });
    wrap(page, dep.recommendation.rationale, left, () => y, (v) => { y = v; }, sans);
    y -= 6;
  }

  if (dep.scorecard.length) {
    line("Operational scorecard", { size: 13, font: sansBold, gap: 18 });
    for (const l of dep.scorecard) {
      line(`${l.label}: ${l.score}`, { font: sansBold, gap: 14 });
      wrap(page, l.note, left + 12, () => y, (v) => { y = v; }, sans, 10, MUTED);
      y -= 4;
    }
  }
  if (dep.endpoints.length) {
    line("Study endpoints", { size: 13, font: sansBold, gap: 18 });
    for (const e of dep.endpoints) {
      line(`${e.kind} · ${e.name} — ${e.met ? "MET" : "MISSED"}`, { font: sansBold, gap: 14 });
      line(`Target ${e.target} · Result ${e.result}`, { size: 10, color: MUTED, gap: 16 });
    }
  }

  if (dep.ownership) {
    y -= 4;
    line("Ownership plan", { size: 13, font: sansBold, gap: 18 });
    for (const [k, v] of [["Runs", dep.ownership.runs], ["Maintains", dep.ownership.maintains], ["Pays", dep.ownership.pays], ["Referral backstop", dep.ownership.referralBackstop], ["Monitoring cadence", dep.ownership.monitoringCadence]] as const) {
      line(`${k}: ${v}`, { size: 10, gap: 15 });
    }
  }

  page.drawText("Generated by ClearPath · post-deployment evaluation report", { x: left, y: 40, size: 8, font: sans, color: MUTED });

  const bytes = await pdf.save();
  const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `clearpath-report-${tool.name.toLowerCase().replace(/\s+/g, "-")}.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Simple word-wrap helper for the rationale/notes. */
function wrap(page: import("pdf-lib").PDFPage, text: string, x: number, getY: () => number, setY: (v: number) => void, font: import("pdf-lib").PDFFont, size = 11, color = INK) {
  const max = 78;
  const words = text.split(/\s+/);
  let lineStr = "";
  for (const w of words) {
    if ((lineStr + " " + w).length > max) {
      page.drawText(lineStr, { x, y: getY(), size, font, color });
      setY(getY() - 14);
      lineStr = w;
    } else {
      lineStr = lineStr ? lineStr + " " + w : w;
    }
  }
  if (lineStr) { page.drawText(lineStr, { x, y: getY(), size, font, color }); setY(getY() - 14); }
}
