import puppeteer from "puppeteer-core";
const CHROME="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const b=await puppeteer.launch({executablePath:CHROME,headless:true,args:["--no-sandbox"]});
const p=await b.newPage(); await p.setViewport({width:1280,height:1400});
const errs=[]; p.on("pageerror",e=>errs.push(String(e)));
const url=process.argv[2];
await p.goto("http://localhost:3000"+url,{waitUntil:"networkidle2"});
await new Promise(r=>setTimeout(r,2600));
const t=await p.evaluate(()=>document.body.innerText);
const low=t.toLowerCase();
console.log("--- assertions ---");
console.log("gates clear:", low.includes("gates clear"), "| has 17:", low.includes("17"), "| no '16 gate':", !low.includes("16 gate"), "| no '/ 16':", !low.includes("/ 16"));
console.log("assessment across four dimensions:", low.includes("assessment across four dimensions"));
console.log("bodh validation score:", low.includes("bodh validation score"), "| accuracy:", low.includes("accuracy"));
console.log("attached evidence:", low.includes("attached evidence"));
console.log("no 94/100 disc:", !/\b\d{2,3}\s?\/\s?100\b/.test(t));
console.log("--- body ---");
console.log(t.split("Login as")[1]?.slice(0,900));
console.log("ERRORS:", errs.join(" | "));
await b.close();
